function Xi_1 = calc_Xi_1(in1,in2)
%calc_Xi_1
%    Xi_1 = calc_Xi_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2024 13:55:28

theta = in2(:,2);
x_dot = in1(3,:);
y_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta.*2.0;
t5 = t2.^2;
t6 = t2.^3;
t7 = sin(t4);
t8 = t2.*x_dot;
t9 = t2.*y_dot;
t10 = t3.*x_dot;
t11 = t6.*x_dot;
t13 = t7./2.0;
t14 = t3.*t5.*y_dot;
t16 = t9+t10;
t12 = -t11;
t15 = -t13;
t17 = 1.0./t16;
t18 = t8+t12+t14;
t19 = t17.*t18;
t20 = -t19;
Xi_1 = reshape([t5,t20,0.0,0.0,t20,-t5+1.0,0.0,0.0,0.0,0.0,t5,t15,0.0,0.0,t15,t3.^2],[4,4]);
end
