function Xi_1 = calc_Xi_1(in1,in2)
%calc_Xi_1
%    Xi_1 = calc_Xi_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Dec-2023 02:17:42

alpha = in2(:,1);
g = in2(:,2);
y_dot = in1(2,:);
t2 = -alpha;
Xi_1 = reshape([t2,-(g.*(alpha+1.0))./y_dot,0.0,t2],[2,2]);
