function f1_disc = calc_f1_disc(in1,uy,dt,in4)
%CALC_F1_DISC
%    F1_DISC = CALC_F1_DISC(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Apr-2025 11:11:01

g = in4(:,2);
m = in4(:,1);
y = in1(1,:);
y_dot = in1(2,:);
f1_disc = [y+dt.*y_dot;y_dot+(dt.*(uy-g.*m))./m];
end
