function out1 = calc_A_lin1(in1,uy,in3)
%calc_A_lin1
%    OUT1 = calc_A_lin1(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Apr-2025 11:11:01

out1 = reshape([0.0,0.0,1.0,0.0],[2,2]);
end
