function DtG1 = calc_Dtg12(t,in2,uy,in4)
%calc_Dtg12
%    DtG1 = calc_Dtg12(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Apr-2025 11:11:00

DtG1 = pi.*cos(t.*pi.*4.0).*(-2.0e-4);
end
