function DtG2 = calc_Dtg21(t,in2,uy,in4)
%calc_Dtg21
%    DtG2 = calc_Dtg21(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Apr-2025 11:11:00

DtG2 = 0.0;
end
