function DG1 = calc_Dg12(in1,uy,in3)
%calc_Dg12
%    DG1 = calc_Dg12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:48

DG1 = [-1.0,0.0];
end
