function B_lin1_disc = calc_B_lin1_disc(in1,uy,dt,in4)
%calc_B_lin1_disc
%    B_lin1_disc = calc_B_lin1_disc(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Feb-2025 18:04:31

m = in4(:,1);
B_lin1_disc = [0.0;dt./m];
end
