function f2 = calc_f2(in1,uy,in3)
%CALC_F2
%    F2 = CALC_F2(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:46

g = in3(:,2);
m = in3(:,1);
y_dot = in1(2,:);
f2 = [y_dot;(uy-g.*m)./m];
end
