function A_lin1_disc = calc_A_lin1_disc(in1,uy,dt,in4)
%calc_A_lin1_disc
%    A_lin1_disc = calc_A_lin1_disc(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:49

A_lin1_disc = reshape([1.0,0.0,dt,1.0],[2,2]);
end
