function B_lin2_disc = calc_B_lin2_disc(in1,uy,dt,in4)
%calc_B_lin2_disc
%    B_lin2_disc = calc_B_lin2_disc(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:50

m = in4(:,1);
B_lin2_disc = [0.0;dt./m];
end
