function DR2 = calc_Dr21(in1,uy,in3)
%calc_Dr21
%    DR2 = calc_Dr21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:47

DR2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
end
