function R1 = calc_r12(in1,uy,in3)
%CALC_R12
%    R1 = CALC_R12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:47

e = in3(:,3);
y = in1(1,:);
y_dot = in1(2,:);
R1 = [y;-e.*y_dot];
end
