function DR1 = calc_Dr12(in1,uy,in3)
%calc_Dr12
%    DR1 = calc_Dr12(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Feb-2025 18:04:30

e = in3(:,3);
DR1 = reshape([1.0,0.0,0.0,-e],[2,2]);
end
