function out1 = calc_B_lin2(in1,uy,in3)
%calc_B_lin2
%    OUT1 = calc_B_lin2(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Dec-2024 11:06:49

m = in3(:,1);
out1 = [0.0;1.0./m];
end
