function salt2 = calc_salt21(t,in2,uy,in4)
%CALC_SALT21
%    SALT2 = CALC_SALT21(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Feb-2025 18:04:31

salt2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
end
