function Xi_1 = calc_Xi_1(in1,in2)
%calc_Xi_1
%    Xi_1 = calc_Xi_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2024 13:46:42

alpha = in2(:,1);
g = in2(:,2);
y_dot = in1(2,:);
Xi_1 = reshape([alpha.^2,-(g.*(alpha+1.0))./y_dot,0.0,-alpha],[2,2]);
end
