function Xi_2 = calc_Xi_2(in1,in2)
%calc_Xi_2
%    Xi_2 = calc_Xi_2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 17:48:11

theta = in2(:,2);
t2 = theta.*2.0;
t3 = sin(t2);
t4 = t3./2.0;
t5 = -t4;
Xi_2 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,cos(theta).^2,t5,0.0,0.0,t5,sin(theta).^2],[4,4]);
