function Xi_1 = calc_Xi_1(in1,in2)
%calc_Xi_1
%    Xi_1 = calc_Xi_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 17:48:11

theta = in2(:,2);
x_dot = in1(3,:);
y_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta.*2.0;
t5 = t2.^2;
t6 = sin(t4);
t7 = t3.^2;
t8 = t6./2.0;
t9 = -t8;
Xi_1 = reshape([-t7+1.0,t9,0.0,0.0,-(t2.*(x_dot-t5.*x_dot+t2.*t3.*y_dot))./(t3.*x_dot+t2.*y_dot),-t5+1.0,0.0,0.0,0.0,0.0,t5,t9,0.0,0.0,t9,t7],[4,4]);
