function Xi_1 = calc_Xi_1(in1,in2)
%calc_Xi_1
%    Xi_1 = calc_Xi_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Dec-2023 03:25:19

theta = in2(:,2);
x_dot = in1(3,:);
y_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.*y_dot;
t5 = t3.*x_dot;
t6 = t4+t5;
t7 = 1.0./t6;
Xi_1 = reshape([t4.*t7,-t3.*t7.*y_dot,0.0,0.0,-t2.*t7.*x_dot,t5.*t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
