function salt1 = calc_salt12(t,in2,uy,in4)
%CALC_SALT12
%    SALT1 = CALC_SALT12(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Feb-2024 03:31:17

e = in4(:,3);
g = in4(:,2);
m = in4(:,1);
y_dot = in2(2,:);
t2 = t.*pi.*4.0;
t3 = cos(t2);
t4 = t3.*pi.*2.0;
t5 = t4+y_dot;
t6 = 1.0./t5;
salt1 = reshape([-t6.*(y_dot+e.*y_dot)+1.0,(t6.*(uy-g.*m).*(e+1.0))./m,0.0,-e],[2,2]);
