function DG2 = calc_Dg21(in1,uy,in3)
%calc_Dg21
%    DG2 = calc_Dg21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2024 09:13:50

DG2 = [0.0,-1.0];
