function G1 = calc_g12(t,in2,uy,in4)
%CALC_G12
%    G1 = CALC_G12(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Feb-2024 03:31:15

y = in2(1,:);
G1 = -y+sin(t.*pi.*4.0)./2.0;
