function out1 = calc_B_lin1(in1,uy,in3)
%calc_B_lin1
%    OUT1 = calc_B_lin1(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2024 09:13:50

m = in3(:,1);
out1 = [0.0;1.0./m];
