function DR2 = calc_Dr21(in1,uy,in3)
%calc_Dr21
%    DR2 = calc_Dr21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2024 09:13:50

DR2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
