function salt2 = calc_salt21(t,in2,uy,in4)
%CALC_SALT21
%    SALT2 = CALC_SALT21(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Feb-2024 03:31:17

salt2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
