function G2 = calc_a2(t,in2,uy,in4)
%CALC_A2
%    G2 = CALC_A2(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Feb-2024 03:31:16

y_dot = in2(2,:);
G2 = -y_dot;
