function out1 = calc_A_lin2(in1,uy,in3)
%calc_A_lin2
%    OUT1 = calc_A_lin2(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Feb-2024 03:31:16

out1 = reshape([0.0,0.0,1.0,0.0],[2,2]);
