function DG2 = calc_Dg21(in1,uy,in3)
%calc_Dg21
%    DG2 = calc_Dg21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Feb-2024 03:31:16

DG2 = [0.0,-1.0];
