function DtG2 = calc_Dtg21(t,in2,uy,in4)
%calc_Dtg21
%    DtG2 = calc_Dtg21(T,IN2,UY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2024 09:13:50

DtG2 = 0.0;
