function A_lin2_disc = calc_A_lin2_disc(in1,uy,dt,in4)
%calc_A_lin2_disc
%    A_lin2_disc = calc_A_lin2_disc(IN1,UY,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Nov-2024 09:13:51

A_lin2_disc = reshape([1.0,0.0,dt,1.0],[2,2]);
