function R2 = calc_r21(in1,uy,in3)
%CALC_R21
%    R2 = CALC_R21(IN1,UY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Apr-2025 11:11:00

y = in1(1,:);
y_dot = in1(2,:);
R2 = [y;y_dot];
end
