function Xi_2 = calc_Xi_2(in1,in2)
%calc_Xi_2
%    Xi_2 = calc_Xi_2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Dec-2023 02:17:42

Xi_2 = reshape([1.0,0.0,0.0,1.0],[2,2]);
